services:
  - type: web
    name: twitter-video-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: FRONTEND_URL
        value: https://twitter-video-downloader-zfb9.vercel.app
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - tsconfig.json
        - src/**
        - scripts/** 